version: '3'

services:
  payload:
    image: node:18.8-slim
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
